# Generated by Django 5.2 on 2025-05-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.paiement')),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='promoteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.promoteur'),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules_in_agence', to='Location_voiture.agence')),
                ('loueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.loueur')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.client')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.location')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.client')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='vehicule',
            field=models.ManyToManyField(related_name='agences_with_vehicule', to='Location_voiture.vehicule'),
        ),
    ]
