# Generated by Django 5.2 on 2025-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_voiture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='name',
            field=models.CharField(default='Default Agency', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Default Client', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loueur',
            name='name',
            field=models.CharField(default='Default Promoteur', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoteur',
            name='name',
            field=models.CharField(default='Default Loueur', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicule',
            name='model',
            field=models.CharField(default='Default Vehicule', max_length=100),
            preserve_default=False,
        ),
    ]
