# Generated by Django 5.2 on 2025-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_voiture', '0002_agence_name_client_name_loueur_name_promoteur_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
