# Generated by Django 5.0 on 2025-06-10 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_voiture', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Agency rating from 0.0 to 5.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='location',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Start date of the rental', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='date_fin',
            field=models.DateField(blank=True, help_text='End date of the rental', null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Rating from 0.0 to 5.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
