# Generated by Django 5.0 on 2025-06-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_voiture', '0004_agence_rating_location_date_debut_location_date_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='loueur',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='client',
            field=models.ForeignKey(default=1, help_text='Vehicle owner/client', on_delete=django.db.models.deletion.CASCADE, to='Location_voiture.client'),
            preserve_default=False,
        ),
    ]
