# Generated by Django 5.0 on 2025-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_voiture', '0007_client_address_client_date_of_birth_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Total amount in DT', max_digits=10),
        ),
    ]
