# Generated by Django 5.2.4 on 2025-07-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Location_voiture",
            "0008_location_payment_date_location_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compte",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="avis",
            name="client",
        ),
        migrations.RemoveField(
            model_name="avis",
            name="vehicule",
        ),
        migrations.DeleteModel(
            name="Loueur",
        ),
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.DeleteModel(
            name="Compte",
        ),
        migrations.DeleteModel(
            name="Avis",
        ),
    ]
